# Notebook para probar sintaxis

In [11]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [16]:
df = pd.read_csv("datasets/car_data.csv")

df.head()

,DateCrawled,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Mileage,RegistrationMonth,FuelType,Brand,NotRepaired,DateCreated,NumberOfPictures,PostalCode,LastSeen
0,24/03/2016 11:52,480,NaN,1993,manual,0,golf,150000,0,petrol,volkswagen,NaN,24/03/2016 00:00,0,70435,07/04/2016 03:16
1,24/03/2016 10:58,18300,coupe,2011,manual,190,NaN,125000,5,gasoline,audi,yes,24/03/2016 00:00,0,66954,07/04/2016 01:46
2,14/03/2016 12:52,9800,suv,2004,auto,163,grand,125000,8,gasoline,jeep,NaN,14/03/2016 00:00,0,90480,05/04/2016 12:47
3,17/03/2016 16:54,1500,small,2001,manual,75,golf,150000,6,petrol,volkswagen,no,17/03/2016 00:00,0,91074,17/03/2016 17:40
4,31/03/2016 17:25,3600,small,2008,manual,69,fabia,90000,7,gasoline,skoda,no,31/03/2016 00:00,0,60437,06/04/2016 10:17

In [18]:
print(df.shape)

(354369, 16)

In [10]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Datos de ejemplo (variables categóricas)
X = pd.DataFrame({
    'Ciudad': ['Madrid', 'París', 'Madrid', 'Tokio'],
    'Tamaño': ['S', 'M', 'L', 'S']
})
display(X)

# 1. Instanciar el encoder
# sparse_output=False devuelve un array normal de NumPy (en versiones antiguas era sparse=False)
encoder = OneHotEncoder(sparse_output=False)

# 2. Ajustar y transformar los datos
X_encoded = encoder.fit_transform(X)
print(X_encoded)
print(X_encoded.dtype)

# 3. Obtener el nombre de las nuevas columnas generadas
columnas_nuevas = encoder.get_feature_names_out(['Ciudad', 'Tamaño'])
print(columnas_nuevas)

# Convertir el resultado a DataFrame para visualizarlo claramente
df_encoded = pd.DataFrame(X_encoded, columns=columnas_nuevas)
print(df_encoded)

   Ciudad Tamaño
0  Madrid      S
1   París      M
2  Madrid      L
3   Tokio      S

[[1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1.]]
float64
['Ciudad_Madrid' 'Ciudad_París' 'Ciudad_Tokio' 'Tamaño_L' 'Tamaño_M'
 'Tamaño_S']
   Ciudad_Madrid  Ciudad_París  Ciudad_Tokio  Tamaño_L  Tamaño_M  Tamaño_S
0            1.0           0.0           0.0       0.0       0.0       1.0
1            0.0           1.0           0.0       0.0       1.0       0.0
2            1.0           0.0           0.0       1.0       0.0       0.0
3            0.0           0.0           1.0       0.0       0.0       1.0

In [22]:
df = pd.read_csv("datasets/car_data.csv")

# Filtros
# --------------------------------------------
# Filtrar registros con precio meno o igual a 0
filter_price = df['Price'] > 0

# Solo registros entre 1980 y 2025
filter_year = df['RegistrationYear'].between(1980, 2025)

# Solo vehículos con potencia entre 30 y 500
filter_power = df['Power'].between(30, 500)

df = df[
    filter_price &
    filter_year &
    filter_power
]

# Nullos
# -------------------------------------------
cat_columns_with_nulls = [
    'VehicleType',
    'Gearbox',
    'Model',
    'FuelType',
    'NotRepaired'
]

for column in cat_columns_with_nulls:
    df[column] = df[column].fillna('unknown')

# features y target
# ----------------------------------------------
y = df['Price']

features = [
    'VehicleType',
    'RegistrationYear',
    'Gearbox',
    'Power',
    'Model',
    'Mileage',
    'RegistrationMonth',
    'FuelType',
    'Brand',
    'NotRepaired'
]

X = df[features]

# Separar columnas numéricas y categoricas
# -----------------------------------------------------
# Esto es necesario porque cada tipo de columna requiere 
# un trantamiento distinto.

numerical_columns = [
    'RegistrationYear',
    'Power',
    'Mileage',
    'RegistrationMonth'
]

categorical_columns = [
    'VehicleType',
    'Gearbox',
    'Model',
    'FuelType',
    'Brand',
    'NotRepaired'
]

# Separar en conjunto de entrenamiento y prueba
# ----------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
)

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

X_train_encoded = encoder.fit_transform(X_train[categorical_columns])
X_train_final = pd.concat([
    X_train[numerical_columns].reset_index(drop=True),
    pd.DataFrame(X_train_encoded, columns=encoder.get_feature_names_out(categorical_columns))
], axis=1)

X_test_encoded = encoder.transform(X_test[categorical_columns])
X_test_final = pd.concat([
    X_test[numerical_columns].reset_index(drop=True),
    pd.DataFrame(X_test_encoded, columns=encoder.get_feature_names_out(categorical_columns))
], axis=1)

display(X_train_final)
display(X_test_final)

,RegistrationYear,Power,Mileage,RegistrationMonth,VehicleType_bus,VehicleType_convertible,VehicleType_coupe,VehicleType_other,VehicleType_sedan,VehicleType_small,...,Brand_sonstige_autos,Brand_subaru,Brand_suzuki,Brand_toyota,Brand_trabant,Brand_volkswagen,Brand_volvo,NotRepaired_no,NotRepaired_unknown,NotRepaired_yes
0,2002,192,150000,6,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2002,103,150000,2,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2006,69,150000,7,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,2016,177,150000,7,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2009,125,90000,10,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227950,1996,60,150000,0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
227951,1998,170,150000,8,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
227952,2006,87,125000,8,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
227953,2005,224,150000,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
227954,2006,326,150000,4,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

,RegistrationYear,Power,Mileage,RegistrationMonth,VehicleType_bus,VehicleType_convertible,VehicleType_coupe,VehicleType_other,VehicleType_sedan,VehicleType_small,...,Brand_sonstige_autos,Brand_subaru,Brand_suzuki,Brand_toyota,Brand_trabant,Brand_volkswagen,Brand_volvo,NotRepaired_no,NotRepaired_unknown,NotRepaired_yes
0,2011,105,150000,8,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,2004,102,150000,5,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2000,54,150000,2,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2004,131,150000,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,2003,95,70000,0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75980,2007,105,150000,10,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
75981,2003,131,150000,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
75982,1999,116,150000,9,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
75983,2006,90,70000,1,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
75984,2001,103,150000,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0